package marcel;

/*
 * Selector.java
 *
 * Created on 19.12.2010, 18:34:36
 */

/**
 *
 * @author Markus
 */
public class Selector extends javax.swing.JPanel {

    /** Creates new form Selector */
    public Selector() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bReset = new javax.swing.JButton();
        bFilter = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        setFocusable(false);

        bReset.setBackground(new java.awt.Color(255, 255, 255));
        bReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reset3.png"))); // NOI18N
        bReset.setBorder(null);
        bReset.setFocusPainted(false);
        bReset.setFocusable(false);
        add(bReset);

        bFilter.setBackground(java.awt.Color.red);
        bFilter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/filter3.png"))); // NOI18N
        bFilter.setBorder(null);
        bFilter.setFocusPainted(false);
        bFilter.setFocusable(false);
        add(bFilter);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.png"))); // NOI18N
        add(jLabel1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton bFilter;
    public javax.swing.JButton bReset;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
