#name: Rust
#
#on:
#  push:
#    tags:
#      - "v*.*.*"
#
#env:
#  CARGO_TERM_COLOR: always
#
#jobs:
#  build_linux:
#
#    runs-on: ubuntu-latest
#
#    steps:
#    - uses: actions/checkout@v3
#    - name: Install cross
#      run: cargo install cross
#    - name: Install dependencies
#      run: sudo apt-get install libatk1.0-dev libgtk-3-dev libgtk-3-dev
#    - name: Install gdk-sys
#      run: cargo add gdk-sys@0.18.0
#    - name: Build x86_64-unknown-linux-gnu
#      run: cross build --target x86_64-unknown-linux-gnu --verbose
##    - name: Build arm-unknown-linux-gnu
##      run: cross build --target arm-unknown-linux-gnueabi --verbose
##    - name: Build aarch64-unknown-linux-gnu
##      run: cross build --target aarch64-unknown-linux-gnu --verbose
#
##  build_windows:
##    runs-on: windows-latest
##    steps:
##      - uses: actions/checkout@v3
##      - name: Install Rust
##        uses: actions-rs/toolchain@v1
##        with:
##          toolchain: stable
##          target: x86_64-pc-windows-msvc
##      - name: Install gdk-sys
##        run: cargo add gdk-sys@0.18.0
##      - name: Build
##        run: cargo build --verbose
##      - name: Run tests
##        run: cargo test --verbose
##
##  build_macos:
##    runs-on: macos-latest
##    steps:
##      - uses: actions/checkout@v3
##      - name: Install Rust
##        uses: actions-rs/toolchain@v1
##        with:
##          toolchain: stable
##          target: x86_64-apple-darwin
##      - name: Install gdk-sys
##        run: cargo add gdk-sys@0.18.0
##      - name: Build
##        run: cargo build --verbose
##      - name: Run tests
##        run: cargo test --verbose